# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[9, 9, 7, 5, 5, 9, 2, 3, 5, 7, 2, 0],
       [7, 3, 4, 7, 4, 3, 4, 7, 6, 9, 4, 3],
       [5, 3, 6, 8, 0, 0, 6, 3, 6, 9, 8, 1],
       [6, 0, 3, 3, 3, 3, 6, 6, 8, 3, 0, 3],
       [8, 3, 9, 1, 7, 0, 5, 8, 1, 8, 9, 8],
       [6, 2, 9, 7, 4, 8, 5, 5, 1, 3, 3, 9],
       [4, 9, 5, 8, 7, 7, 4, 0, 1, 2, 4, 4],
       [1, 6, 9, 2, 1, 9, 5, 4, 9, 6, 7, 2],
       [9, 7, 0, 0, 3, 3, 3, 2, 2, 2, 7, 8],
       [8, 4, 7, 0, 6, 4, 2, 4, 1, 0, 8, 4],
       [6, 2, 2, 8, 3, 9, 5, 8, 8, 9, 6, 0],
       [7, 7, 5, 3, 9, 6, 8, 5, 6, 3, 5, 0]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),np.int)

<ipython-input-9-6137fcb8b1c2>:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dst = np.zeros((h,w),np.int)


In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[9, 9, 7, 5, 5, 9, 2, 3, 5, 7, 2, 0],
       [7, 3, 4, 7, 4, 3, 4, 7, 6, 9, 4, 3],
       [5, 3, 6, 8, 0, 0, 6, 3, 6, 9, 8, 1],
       [6, 0, 3, 3, 3, 3, 6, 6, 8, 3, 0, 3],
       [8, 3, 9, 1, 7, 0, 5, 8, 1, 8, 9, 8],
       [6, 2, 9, 7, 4, 8, 5, 5, 1, 3, 3, 9],
       [4, 9, 5, 8, 7, 7, 4, 0, 1, 2, 4, 4],
       [1, 6, 9, 2, 1, 9, 5, 4, 9, 6, 7, 2],
       [9, 7, 0, 0, 3, 3, 3, 2, 2, 2, 7, 8],
       [8, 4, 7, 0, 6, 4, 2, 4, 1, 0, 8, 4],
       [6, 2, 2, 8, 3, 9, 5, 8, 8, 9, 6, 0],
       [7, 7, 5, 3, 9, 6, 8, 5, 6, 3, 5, 0]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -11,  -7,   7,   1,  -5,  -2,  12,  -3,  10,  -6,   0],
       [  0,  -2,   6,  16, -15, -12,  11, -13,  -2,  10,  18,   0],
       [  0, -15,  -6,  -3,  -1,   3,   4,  -1,  16, -13, -23,   0],
       [  0,  -7,  20, -22,  20, -23,   1,  15, -21,  16,  17,   0],
       [  0, -19,  13,   6, -13,  16,  -2,   6,  -6,  -2, -13,   0],
       [  0,  19, -15,  11,   8,   0,  -1, -14,  -8,  -6,   0,   0],
       [  0,  -2,  23, -10, -17,  20,   0,   0,  23,   4,   9,   0],
       [  0,   9, -23,  -5,   2,  -7,   0,  -5,  -6,  -7,   3,   0],
       [  0,  -8,  22, -21,  14,  -4,  -8,   3, -10, -20,  15,   0],
       [  0, -11, -14,  24, -20,  18,  -7,  10,   8,  19,   2,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()